name: Rails App Ci

on:
  push:

env:
  RAILS_ENV: test
  DATABASE_URL: "postgres://postgres:password@localhost:5432/cloud_fund_app_test"
  TZ: 'Asia/Tokyo'

jobs:
  rspec:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: cloud_fund_app_test
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: Install dependent libralies
        run: sudo apt-get install libpq-dev

      - name: Cache Gem Directory
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-

      - name: bundler
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Setup Database
        run: |
          bundle exec rake db:create
          bundle exec rake db:schema:load

      - name: install tailwind css
        run: bundle exec rails tailwindcss:install

      - name: Run rspec
        run: bundle exec rspec  --require rails_helper
