name: Rails App Ci

on:
  push:

env:
  RAILS_ENV: test
  DATABASE_URL: "postgres://postgres:password@localhost:5432/myapp_test"
  TZ: 'Asia/Tokyo'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: myapp_test
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    #       redis:
    #         image: redis:alpine
    #         ports:
    #           - 6379:6379
    #         options: --health-cmd "redis-cli -h localhost ping" --health-interval 10s --health-timeout 5s --health-retries 15
    #         env:
    #           REDIS_HOST: redis
    #           REDIS_PORT: 6379
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      #     - name: Set up node
      #       uses: actions/setup-node@v1
      #       with:
      #         node-version: '12'

      - name: Install dependent libralies
        run: sudo apt-get install libpq-dev

      - name: Cache Gem Directory
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-

      #     - name: Cache Npm
      #       uses: actions/cache@v2
      #       with:
      #         path: ~/.npm
      #         key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      #         restore-keys: |
      #           ${{ runner.os }}-node-

      - name: bundler
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      #     - name: yarn install
      #       run: |
      #         yarn install

      #     - name: webpacker compile
      #       run: |
      #         bundle exec rails webpacker:compile

      - name: Setup Database
        run: |
          bundle exec rake db:create
          bundle exec rake db:schema:load

      - name: Run rspec
        run: bundle exec rspec  --require rails_helper
